### ISSUE TITLE
Cleanup in aliases bouncerscript double-check against

### ISSUE THREAD

**Issue by MihaiTabara** [mozilla-releng/bouncerscript#35]
While shipping TB60, bouncerscript sanity caught some error that `thunderbird-esr-next-latest` didn't exist on bouncer. Which was true. We don't have that neither in bouncerscript regexes, nor in bouncer.  
While this issue alone is dealt with in separate bugs, I did want to take a moment and double-check we're up-to-date with entries in bouncer aliases.

Ran a quick script to double-check what we currently have under https://github.com/mozilla-releng/bouncerscript/blob/master/bouncerscript/constants.py#L1 against official bouncer entries and I got:

```
(Pdb) pp official_set.difference(our_set)
{'firefox-esr52-latest-ssl', 'firefox-esr52-latest'}
(Pdb) pp our_set.difference(official_set)
{'thunderbird-latest-ssl',
 'thunderbird-next-latest',
 'thunderbird-next-latest-ssl'}
```

So:
1. We don't have the esr52 aliases included here. That's expected since that's not subject to bouncerscript these days.
2. We have three additional aliases defined in our regexes that are nowhere to be found in bouncer, so most likely never used by other pieces of automation.

@tomprince: are we okay with removing these three aliases below from our sanity validation check? 
CCing @JohanLorenzo 
```
{'thunderbird-latest-ssl',
 'thunderbird-next-latest',
 'thunderbird-next-latest-ssl'}
```

**Comment by lundjordan** [comment]
@MihaiTabara does this still apply?

**Comment by MihaiTabara** [comment]
Yes, still applies. I think the question. Last Thunderbird release looks like this (from [here](https://tools.taskcluster.net/groups/SKhkmQfpTJS5b_LwyDMcDQ/tasks/Vz2-uZkGR2mPRl4s5O9-Zg/details)):

```
{
  "aliases_entries": {
    "thunderbird-latest": "Thunderbird-60.6.1",
    "thunderbird-latest-ssl": "Thunderbird-60.6.1-SSL"
  }
}
```

while the bouncerscript `constants.py` still has two of the three aforementioned aliases which are unused, mainly: 

```
{'thunderbird-next-latest',
 'thunderbird-next-latest-ssl'}
```

@tomprince can I clean the two aliases above from [here](https://github.com/mozilla-releng/bouncerscript/blob/master/bouncerscript/constants.py#L4) since they are unused?

**Comment by tomprince** [comment]
> @tomprince can I clean the two aliases above from [here](https://github.com/mozilla-releng/bouncerscript/blob/master/bouncerscript/constants.py#L4) since they are unused?

Yes.
